### ISSUE TITLE
PCD_DumpVersionToSerial()  -> No member with that name

### ISSUE THREAD

**Issue by Fieldagent** [konstantin-kelemen/arduino-amiibo-tools#1]
Hi,

I'm currently getting this error when I'm trying to compile the DumpInfo on the Arduino IDE.

Arduino: 1.8.2 (Mac OS X), Board: "Arduino/Genuino Uno"

/Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/mbp15/Documents/Arduino/libraries -fqbn=arduino:avr:uno -vid-pid=0X2341_0X0001 -ide-version=10802 -build-path /var/folders/kt/0yggbpvn0bd4ss3kctm15mjr0000gn/T/arduino_build_508116 -warnings=none -build-cache /var/folders/kt/0yggbpvn0bd4ss3kctm15mjr0000gn/T/arduino_cache_888347 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.arduinoOTA.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avr-gcc.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -verbose /Users/mbp15/Downloads/arduino-amiibo-tools-master/Dump_amiibo/Dump_amiibo.ino
/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/mbp15/Documents/Arduino/libraries -fqbn=arduino:avr:uno -vid-pid=0X2341_0X0001 -ide-version=10802 -build-path /var/folders/kt/0yggbpvn0bd4ss3kctm15mjr0000gn/T/arduino_build_508116 -warnings=none -build-cache /var/folders/kt/0yggbpvn0bd4ss3kctm15mjr0000gn/T/arduino_cache_888347 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.arduinoOTA.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avr-gcc.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -verbose /Users/mbp15/Downloads/arduino-amiibo-tools-master/Dump_amiibo/Dump_amiibo.ino
Using board 'uno' from platform in folder: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr
Using core 'arduino' from platform in folder: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr
Detecting libraries used...
"/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "/var/folders/kt/0yggbpvn0bd4ss3kctm15mjr0000gn/T/arduino_build_508116/sketch/Dump_amiibo.ino.cpp" -o "/dev/null"
"/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SPI/src" "/var/folders/kt/0yggbpvn0bd4ss3kctm15mjr0000gn/T/arduino_build_508116/sketch/Dump_amiibo.ino.cpp" -o "/dev/null"
"/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SPI/src" "-I/Users/mbp15/Documents/Arduino/libraries/MFRC522_RFID_Lib" "/var/folders/kt/0yggbpvn0bd4ss3kctm15mjr0000gn/T/arduino_build_508116/sketch/Dump_amiibo.ino.cpp" -o "/dev/null"
"/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SPI/src" "-I/Users/mbp15/Documents/Arduino/libraries/MFRC522_RFID_Lib" "/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SPI/src/SPI.cpp" -o "/dev/null"
"/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SPI/src" "-I/Users/mbp15/Documents/Arduino/libraries/MFRC522_RFID_Lib" "/Users/mbp15/Documents/Arduino/libraries/MFRC522_RFID_Lib/MFRC522.cpp" -o "/dev/null"
Generating function prototypes...
"/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SPI/src" "-I/Users/mbp15/Documents/Arduino/libraries/MFRC522_RFID_Lib" "/var/folders/kt/0yggbpvn0bd4ss3kctm15mjr0000gn/T/arduino_build_508116/sketch/Dump_amiibo.ino.cpp" -o "/var/folders/kt/0yggbpvn0bd4ss3kctm15mjr0000gn/T/arduino_build_508116/preproc/ctags_target_for_gcc_minus_e.cpp"
"/Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "/var/folders/kt/0yggbpvn0bd4ss3kctm15mjr0000gn/T/arduino_build_508116/preproc/ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SPI/src" "-I/Users/mbp15/Documents/Arduino/libraries/MFRC522_RFID_Lib" "/var/folders/kt/0yggbpvn0bd4ss3kctm15mjr0000gn/T/arduino_build_508116/sketch/Dump_amiibo.ino.cpp" -o "/var/folders/kt/0yggbpvn0bd4ss3kctm15mjr0000gn/T/arduino_build_508116/sketch/Dump_amiibo.ino.cpp.o"
/Users/mbp15/Downloads/arduino-amiibo-tools-master/Dump_amiibo/Dump_amiibo.ino: In function 'void setup()':
Dump_amiibo:28: error: 'class MFRC522' has no member named 'PCD_DumpVersionToSerial'
   mfrc522.PCD_DumpVersionToSerial();  // Show details of PCD - MFRC522 Card Reader details
           ^
Using library SPI at version 1.0 in folder: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SPI 
Using library MFRC522_RFID_Lib in folder: /Users/mbp15/Documents/Arduino/libraries/MFRC522_RFID_Lib (legacy)
exit status 1
'class MFRC522' has no member named 'PCD_DumpVersionToSerial'

**Comment by konstantin-kelemen** [comment]
Hi!

What version of the MFRC522 library do you use? How did you install it?

Try to install/update it via Arduino IDE: Sketch → Include Library → Manage Libraries...

Also check for "PCD_DumpVersionToSerial" line in the code of the library you have installed.
Run in terminal:

`grep -R "PCD_DumpVersionToSerial" ~/Documents/Arduino/libraries/MFRC522`

Since the DumpInfo sketch is a part of the MFRC522 library I would recommend you to create an issue at the corresponding repo: https://github.com/miguelbalboa/rfid/issues

**Comment by konstantin-kelemen** [comment]
Seems like there was such issue which should be fixed now: https://github.com/miguelbalboa/rfid/issues/207

**Comment by Fieldagent** [comment]
I updated to the latest through the arduino IDE, so the initial text I get from serial interface is:

Fi1.0
Arduino Amiibo writer. Put your NFC-tag to the reader
Firmware Version: 0x91 = v1.0
Arduino Amiibo writer. Put your NFC-tag to the reader


I know what was my problem previously for the PCD_DumpVersionToSerial() was that I had 2 versions of the MFRC522 libraries on the libraries folder. Now it compiles, but I get the following error when writing to the mifare ultralight nfc tag:

For every line to be written to the tag, i get:

MIFARE_Write() failed: Error in communication.
MIFARE_Write() failed: A MIFARE PICC responded with NAK.
MIFARE_Write() failed: Timeout in communication.



Thanks for your assistance, I truly appreciate your help

**Comment by konstantin-kelemen** [comment]
Seems like you're trying to write to the locked/password protected tag.

If you know the password, you may unlock it (should make a sketch for that), otherwise just try to use another tag.

**Comment by Fieldagent** [comment]
But the tag that I'm writing to is one of those off of ebay tags... I'll try with other ones... do sticker mifare ultralight tags differ a lot from ntag215 tags? if so maybe that's where I'm going wrong. 

Thanks

**Comment by konstantin-kelemen** [comment]
Can you provide a link to tags you have?

You definitely need ntag215 tags. No other tags are supported.

**Comment by Fieldagent** [comment]
These are the ones, not the same seller but that's what I got

http://www.ebay.ca/itm/RFID-Labels-25mm-Round-MIFARE-Ultralight-White-13-56-MHz-Pack-10pcs-/322444196822?hash=item4b132bfbd6:g:zwMAAOSwSlBYvdrh

**Comment by konstantin-kelemen** [comment]
Unfortunately these tags will not work. They don't even have enough memory to hold the dump. Guess that's why you had a write error in the middle of the writing process.

Better get [these tags](http://s.click.aliexpress.com/e/nIuz3Rj). They work great and have a better form-factor.
