### ISSUE TITLE
Outdated MFRC522 library causing poor communication between NFC tag and RFID module

### ISSUE THREAD

**Issue by ctomlin14** [konstantin-kelemen/arduino-amiibo-tools#12]
I'm using an [Arduino Uno R3](https://www.amazon.com/gp/product/B008GRTSV6/ref=ppx_yo_dt_b_search_asin_image?ie=UTF8&th=1), [HiLetGo RC522 modules](https://www.amazon.com/gp/product/B07VLDSYRW/ref=ppx_yo_dt_b_search_asin_image?ie=UTF8&psc=1), and [BABIQT NTAG215 tags](https://www.amazon.com/gp/product/B0B617HLLF/ref=ppx_yo_dt_b_search_asin_image?ie=UTF8&th=1).

The MFRC522 library currently included in this project is outdated and is causing significant connection/communication issues with any RFID/NFC tag. With the old library in place I was only able to successfully write to three NFC tags after countless attempts, and I had to find the exact right positioning for it to work. I even tried multiple RC522 modules in case one was broken, but to no avail. The success rate was abysmally low.

After a few hours of troubleshooting, I realized the [updated MFRC522](https://github.com/miguelbalboa/rfid) library solves this problem perfectly, and after successfully swapping this out and re-uploading the Arduino sketch, I now get successful writes every single time. The new MFRC522 library I used can be found here: [https://github.com/miguelbalboa/rfid](https://github.com/miguelbalboa/rfid)

The proposed fix here is to simply update the included MFRC522 library with the latest release.

**Comment by konstantin-kelemen** [comment]
Hi, @ctomlin14 
The code in this repository doesn't include any libraries. MFRC522 library is required to run the code, which is mentioned in the Readme, with a link to the same library you've mentioned.
Am I missing something?

**Comment by ctomlin14** [comment]
Whoops! My bad. I accidentally logged this issue against your project when I intended to log it against [this one](https://github.com/Patriack/AmiiBomb). Your project was actually the one I was comparing against when the Amiibomb one wasn't working right, so thank you for your working example which helped me find the issue with the library!

Anyway, absolutely ignore this. I'll go submit this to the proper project now.

**Comment by ctomlin14** [comment]
This was accidentally submitted against the wrong project. It can be ignored.
