### ISSUE TITLE
Easy Fix

### ISSUE THREAD

**Issue by knil92** [konstantin-kelemen/arduino-amiibo-tools#3]
Hey, 

So the link to the blog post doesnt work, and I would love to be able to figure this out, I've had an nfc reader module laying around for some time now and I havent really figured out what i could use it for, until i sarted buying amiibo's, I just want to be able to take them with me and not have to haul around a box full of toys. If you could provide the instructions that was on the blog post it would be a great help.

Thanks,
Knil92

**Comment by konstantin-kelemen** [comment]
Hi, @knil92!

I just checked and the blog post is loading fine. 

I got reports from people that my blog is blocked by Avast for some unknown reason. Are you using Avast by any chance? If so, I would recommend you to whitelist my blog until I figure out how to fix that. Unfortunately, I haven't got any news from Avast support yet.

Also if you can't do anything with the firewall/antivirus from your side, I also made a copy of the blog post in the project's wiki: https://github.com/konstantin-kelemen/arduino-amiibo-tools/wiki/Create-amiibo-clones-with-Arduino

Enjoy!
