### ISSUE TITLE
Odd issue

### ISSUE THREAD

**Issue by SirBedwyr** [konstantin-kelemen/arduino-amiibo-tools#5]
I put together your system and oddly while it does not work for either Switch or 3DS, it does work for a friend's Android NFC reader which correctly identifies the Amiibo type.

I use the same hardware including an Uno and RC522. I use cards the same as or similar to the ones you suggest on AliExpress (UID: 0492F662AE4F80). I haven't seen any system issues or errors in the code. Switch (BotW) gives no feedback and Yoshi Wooly World gives a "could not read data" error message. Do you have any suggestions for troubleshooting?

**Comment by konstantin-kelemen** [comment]
Hi, make sure you follow the instructions and do the cloning correctly.
Also try [AmiiBomb](https://gbatemp.net/threads/tools-amiibomb.467990/) and [AmiiDuino](https://francescpaez.com/clonar-amiibos-con-arduino/), the tools which make the process even simpler.
