### ISSUE TITLE
hello,about https://games.kel.mn/amiibo/ page

### ISSUE THREAD

**Issue by NinthCode** [konstantin-kelemen/arduino-amiibo-tools#7]
hello:
First,thank you for the code, use your code to make my [ESP32] work.
but,i think write a function,upload the bin file with [ESP32]web page,next write ntag215,But I noticed that you need to decrypt the bin file with the webpage[https://games.kel.mn/amiibo/] you provided, so can you please provide the code or ideas for this page?

**Comment by konstantin-kelemen** [comment]
Hi,

you can find the code here: https://github.com/konstantin-kelemen/amiibo-online-tool
Also take a look at Wifiibo, a project that implements all the amiibo processing on ESP8266: https://github.com/Xerxes3rd/Wifiibo
